# Github Action의 DB 동기화 텀을 조절하는 yml

name: Hourly SQLite->MySQL Sync
on:
  schedule:
    - cron: "0 * * * *"   # 매시 정각 (UTC 기준 주의)
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    concurrency:
      group: hourly-sync
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install sqlalchemy pymysql
      - env:
          SQLITE_URL: ${{ secrets.SQLITE_URL }}   # 예: s3://... 또는 sqlite:////path
          MYSQL_URL:  ${{ secrets.MYSQL_URL }}    # RDS 접속 DSN
          SOURCE_NAME: sqlite_docs
          SQLITE_TABLE: app_product
        run: python sqlite2mysql/sync_sqlite_to_mysql.py
